"""Create Skill table

Revision ID: 1fe633e19aab
Revises:
Create Date: 2023-02-16 14:00:21.045634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = "1fe633e19aab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "skills",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, index=True),
        sa.Column("start_date", sa.Date),
        sa.Column("created_at", sa.DateTime, server_default=func.now()),
        sa.Column(
            "last_updated_at",
            sa.DateTime,
            server_default=func.now(),
            server_onupdate=func.now(),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
