"""added projects

Revision ID: 20e52386897b
Revises: 82d4b4ba57e0
Create Date: 2023-02-20 11:42:49.593298

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func


# revision identifiers, used by Alembic.
revision = "20e52386897b"
down_revision = "82d4b4ba57e0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("name", sa.String, index=True),
        sa.Column("url", sa.String),
        sa.Column("created_at", sa.DateTime, server_default=func.now()),
        sa.Column(
            "updated_at",
            sa.DateTime,
            server_default=func.now(),
            server_onupdate=func.now(),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
